// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSXluKJgeUpqnKepo1ppE_9glKJUj3QEQ',
    appId: '1:204596669709:web:12962d9dd3046f40915444',
    messagingSenderId: '204596669709',
    projectId: 'kiangthai-services',
    authDomain: 'kiangthai-services.firebaseapp.com',
    storageBucket: 'kiangthai-services.firebasestorage.app',
    measurementId: 'G-8LGG3KZV16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFabVjFYgkvpFRMujTKqH8nrC1JKRyxxs',
    appId: '1:204596669709:android:0fd6e30dae03ae24915444',
    messagingSenderId: '204596669709',
    projectId: 'kiangthai-services',
    storageBucket: 'kiangthai-services.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJC03EtQRObyKPSU3uroam-82AojALSdg',
    appId: '1:204596669709:ios:1f8ec555dd3fff67915444',
    messagingSenderId: '204596669709',
    projectId: 'kiangthai-services',
    storageBucket: 'kiangthai-services.firebasestorage.app',
    iosBundleId: 'com.kiangthai.services.kiangthaiServices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJC03EtQRObyKPSU3uroam-82AojALSdg',
    appId: '1:204596669709:ios:1f8ec555dd3fff67915444',
    messagingSenderId: '204596669709',
    projectId: 'kiangthai-services',
    storageBucket: 'kiangthai-services.firebasestorage.app',
    iosBundleId: 'com.kiangthai.services.kiangthaiServices',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSXluKJgeUpqnKepo1ppE_9glKJUj3QEQ',
    appId: '1:204596669709:web:77b694ab6209810a915444',
    messagingSenderId: '204596669709',
    projectId: 'kiangthai-services',
    authDomain: 'kiangthai-services.firebaseapp.com',
    storageBucket: 'kiangthai-services.firebasestorage.app',
    measurementId: 'G-CGFY69DYZG',
  );
}
